# Generated by Django 4.2.5 on 2023-10-23 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_profile_model_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
