# Generated by Django 4.2.5 on 2023-10-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_sellerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
