# Generated by Django 4.2.5 on 2023-10-31 13:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('Auction_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('about_product', ckeditor.fields.RichTextField()),
                ('auction_start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('auction_end_datetime', models.DateTimeField()),
                ('image1', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('authentication_certificate', models.FileField(upload_to='certificates/')),
                ('sold', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.sellerprofile')),
            ],
        ),
    ]
