# Generated by Django 4.2.5 on 2024-01-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0004_cart_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reauction', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.addproduct')),
            ],
        ),
    ]
