# Generated by Django 4.2.5 on 2024-01-27 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0005_rejectedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.addproduct')),
            ],
        ),
    ]
