# Generated by Django 4.2.5 on 2024-02-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
