# Generated by Django 4.2.5 on 2024-03-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0020_deliveryboy_deliveryassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAssignment',
        ),
    ]
