# Generated by Django 4.2.5 on 2024-03-27 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0022_deliveryassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('delivery_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.deliveryassignment')),
            ],
        ),
    ]
